### ISSUE TITLE
missing hyq.srdf file

### ISSUE THREAD

**Issue by rohanpsingh** [stonneau/hpp-rbprm-corba#12]
running the command: 

> $ ./run.sh darpa_hyq.py

runs into this error:
>Error: hpp.Error(msg='FLOATING joints are not supported')

changing the joint type from floating to fixed at line 66 of hyq.urdf  (or using hyq.urdf.xacro instead of hyq_model.urdf.xacro to create hyq.urdf) results in error of missing hyq.srdf file !

![git_issue](https://user-images.githubusercontent.com/16384313/41028831-377d9db8-69b5-11e8-9908-6079d36cb979.png)

What does the value of joint type actually need to be? And how to create/retrieve the srdf file?

Thanks!
Rohan

**Comment by stonneau** [comment]
Hi, apparently the urdf model of HyQ has changed since the paper was written.
I m going to update the documentation accordingly. Please consider using the 
hyq model given at the following address:

https://cloud.laas.fr/index.php/s/ydRq3DoBz2LYMLS

You shoud unzip it in

$DEVEL_DIR/install/share/hyq_description/

Sincerely

Steve

**Comment by rohanpsingh** [comment]
Thanks! the script seems to be running fine now.

-Rohan
